/** Field types for PalWorldSettings.ini OptionSettings */
export type IniFieldType =
  | "boolean"
  | "number"
  | "string"
  | "enum"
  | "stringList";

export type IniCategory =
  | "performance"
  | "server"
  | "features"
  | "balances";

export interface IniFieldDef {
  key: string;
  type: IniFieldType;
  category: IniCategory;
  label: string;
  description: string;
  /** Sensitive — mask in UI */
  sensitive?: boolean;
  enumValues?: string[];
  min?: number;
  max?: number;
  default?: string | number | boolean | string[];
}

/**
 * Full documented PalWorldSettings.ini OptionSettings schema.
 * Source: https://docs.palworldgame.com/settings-and-operation/configuration
 */
export const INI_FIELDS: IniFieldDef[] = [
  // --- Performance ---
  {
    key: "BaseCampMaxNum",
    type: "number",
    category: "performance",
    label: "Base Camp Max Num",
    description: "Total number of bases across the server.",
    default: 128,
  },
  {
    key: "BaseCampMaxNumInGuild",
    type: "number",
    category: "performance",
    label: "Base Camp Max Per Guild",
    description: "Maximum number of bases per guild. Default: 4 (max 10).",
    min: 1,
    max: 10,
    default: 4,
  },
  {
    key: "BaseCampWorkerMaxNum",
    type: "number",
    category: "performance",
    label: "Base Camp Worker Max",
    description: "Maximum number of Pals per base (max 50).",
    min: 1,
    max: 50,
    default: 20,
  },
  {
    key: "ItemContainerForceMarkDirtyInterval",
    type: "number",
    category: "performance",
    label: "Item Container Sync Interval",
    description:
      "How often to force re-sync while a container UI is open (seconds).",
    default: 1,
  },
  {
    key: "MaxBuildingLimitNum",
    type: "number",
    category: "performance",
    label: "Max Building Limit",
    description: "Per-player building count cap (0 = unlimited).",
    min: 0,
    default: 0,
  },
  {
    key: "PhysicsActiveDropItemMaxNum",
    type: "number",
    category: "performance",
    label: "Physics Active Drop Item Max",
    description: "Maximum number of dropped items that can use physics behavior.",
    default: 100,
  },
  {
    key: "ServerReplicatePawnCullDistance",
    type: "number",
    category: "performance",
    label: "Pawn Cull Distance",
    description: "Pal sync distance from players (cm). Min 5000 – max 15000.",
    min: 5000,
    max: 15000,
    default: 15000,
  },

  // --- Server management ---
  {
    key: "ServerName",
    type: "string",
    category: "server",
    label: "Server Name",
    description: "Server name shown in the browser.",
    default: "Default Palworld Server",
  },
  {
    key: "ServerDescription",
    type: "string",
    category: "server",
    label: "Server Description",
    description: "Server description.",
    default: "",
  },
  {
    key: "AdminPassword",
    type: "string",
    category: "server",
    label: "Admin Password",
    description: "Password used for admin privileges and REST API Basic Auth.",
    sensitive: true,
    default: "",
  },
  {
    key: "ServerPassword",
    type: "string",
    category: "server",
    label: "Server Password",
    description: "Password required to join the server.",
    sensitive: true,
    default: "",
  },
  {
    key: "ServerPlayerMaxNum",
    type: "number",
    category: "server",
    label: "Max Players",
    description: "Maximum number of players who can join.",
    min: 1,
    max: 32,
    default: 32,
  },
  {
    key: "PublicIP",
    type: "string",
    category: "server",
    label: "Public IP",
    description: "Community server: explicit external public IP.",
    default: "",
  },
  {
    key: "PublicPort",
    type: "number",
    category: "server",
    label: "Public Port",
    description:
      "Community server: explicit external public port (does not change listen port).",
    default: 8211,
  },
  {
    key: "RCONEnabled",
    type: "boolean",
    category: "server",
    label: "RCON Enabled",
    description: "Enable RCON (legacy; prefer REST API).",
    default: false,
  },
  {
    key: "RCONPort",
    type: "number",
    category: "server",
    label: "RCON Port",
    description: "Port number used for RCON.",
    default: 25575,
  },
  {
    key: "RESTAPIEnabled",
    type: "boolean",
    category: "server",
    label: "REST API Enabled",
    description: "Enable the official REST API.",
    default: true,
  },
  {
    key: "RESTAPIPort",
    type: "number",
    category: "server",
    label: "REST API Port",
    description: "Listening port for the REST API.",
    default: 8212,
  },
  {
    key: "bIsUseBackupSaveData",
    type: "boolean",
    category: "server",
    label: "Use Backup Save Data",
    description: "Enable world backups (increases disk load).",
    default: true,
  },
  {
    key: "LogFormatType",
    type: "enum",
    category: "server",
    label: "Log Format",
    description: "Log format: Text or Json.",
    enumValues: ["Text", "Json"],
    default: "Text",
  },
  {
    key: "CrossplayPlatforms",
    type: "stringList",
    category: "server",
    label: "Crossplay Platforms",
    description: "Allowed platforms. Default: Steam, Xbox, PS5, Mac.",
    default: ["Steam", "Xbox", "PS5", "Mac"],
  },
  {
    key: "bAllowClientMod",
    type: "boolean",
    category: "server",
    label: "Allow Client Mods",
    description: "Allow players with mods enabled to join.",
    default: false,
  },
  {
    key: "bIsShowJoinLeftMessage",
    type: "boolean",
    category: "server",
    label: "Show Join/Leave Messages",
    description: "Show in-game messages when players join/leave.",
    default: true,
  },
  {
    key: "bEnableBuildingPlayerUIdDisplay",
    type: "boolean",
    category: "server",
    label: "Show Building Creator ID",
    description: "Display the creator's player ID on structures.",
    default: false,
  },
  {
    key: "ChatPostLimitPerMinute",
    type: "number",
    category: "server",
    label: "Chat Limit Per Minute",
    description: "Maximum chat messages allowed per minute.",
    min: 0,
    default: 10,
  },

  // --- Features ---
  {
    key: "bIsPvP",
    type: "boolean",
    category: "features",
    label: "PvP",
    description: "Enable PvP.",
    default: false,
  },
  {
    key: "bHardcore",
    type: "boolean",
    category: "features",
    label: "Hardcore",
    description: "Enable Hardcore. You cannot respawn on death.",
    default: false,
  },
  {
    key: "bCharacterRecreateInHardcore",
    type: "boolean",
    category: "features",
    label: "Recreate Character in Hardcore",
    description: "Allow recreating character upon death in Hardcore.",
    default: false,
  },
  {
    key: "bEnableFastTravel",
    type: "boolean",
    category: "features",
    label: "Fast Travel",
    description: "Enable fast travel.",
    default: true,
  },
  {
    key: "bEnableFastTravelOnlyBaseCamp",
    type: "boolean",
    category: "features",
    label: "Fast Travel Bases Only",
    description: "Restrict fast travel to between bases only.",
    default: false,
  },
  {
    key: "bEnableInvaderEnemy",
    type: "boolean",
    category: "features",
    label: "Invaders",
    description: "Enable Invader events.",
    default: true,
  },
  {
    key: "bEnableVoiceChat",
    type: "boolean",
    category: "features",
    label: "Voice Chat",
    description: "Enable in-game voice chat.",
    default: false,
  },
  {
    key: "VoiceChatMaxVolumeDistance",
    type: "number",
    category: "features",
    label: "Voice Chat Max Volume Distance",
    description: "Distance at which voice chat volume does not attenuate.",
    default: 2000,
  },
  {
    key: "VoiceChatZeroVolumeDistance",
    type: "number",
    category: "features",
    label: "Voice Chat Zero Volume Distance",
    description: "Distance at which voice chat volume becomes zero.",
    default: 4000,
  },
  {
    key: "RandomizerType",
    type: "enum",
    category: "features",
    label: "Randomizer Type",
    description: "Pal spawn randomization: None, Region, or All.",
    enumValues: ["None", "Region", "All"],
    default: "None",
  },
  {
    key: "RandomizerSeed",
    type: "string",
    category: "features",
    label: "Randomizer Seed",
    description: "Seed used when Pal spawn randomization is enabled.",
    default: "",
  },
  {
    key: "bIsRandomizerPalLevelRandom",
    type: "boolean",
    category: "features",
    label: "Randomizer Pal Level Random",
    description:
      "If true, wild Pal levels are fully random; if false, within area range.",
    default: false,
  },
  {
    key: "bAutoResetGuildNoOnlinePlayers",
    type: "boolean",
    category: "features",
    label: "Auto Reset Empty Guilds",
    description:
      "If no guild members log in, automatically delete structures and base Pals.",
    default: false,
  },
  {
    key: "AutoResetGuildTimeNoOnlinePlayers",
    type: "number",
    category: "features",
    label: "Auto Reset Guild Time (hours)",
    description: "Offline duration before auto-reset triggers.",
    default: 72,
  },
  {
    key: "bAllowGlobalPalboxExport",
    type: "boolean",
    category: "features",
    label: "Global Palbox Export",
    description: "Allow saving to the Global Palbox.",
    default: true,
  },
  {
    key: "bAllowGlobalPalboxImport",
    type: "boolean",
    category: "features",
    label: "Global Palbox Import",
    description: "Allow loading from the Global Palbox.",
    default: true,
  },
  {
    key: "bAllowEnhanceStat_Attack",
    type: "boolean",
    category: "features",
    label: "Allow Stat: Attack",
    description: "Allow allocating stat points to Attack.",
    default: true,
  },
  {
    key: "bAllowEnhanceStat_Health",
    type: "boolean",
    category: "features",
    label: "Allow Stat: Health",
    description: "Allow allocating stat points to HP.",
    default: true,
  },
  {
    key: "bAllowEnhanceStat_Stamina",
    type: "boolean",
    category: "features",
    label: "Allow Stat: Stamina",
    description: "Allow allocating stat points to Stamina.",
    default: true,
  },
  {
    key: "bAllowEnhanceStat_Weight",
    type: "boolean",
    category: "features",
    label: "Allow Stat: Weight",
    description: "Allow allocating stat points to Carry Weight.",
    default: true,
  },
  {
    key: "bAllowEnhanceStat_WorkSpeed",
    type: "boolean",
    category: "features",
    label: "Allow Stat: Work Speed",
    description: "Allow allocating stat points to Work Speed.",
    default: true,
  },
  {
    key: "bBuildAreaLimit",
    type: "boolean",
    category: "features",
    label: "Build Area Limit",
    description: "Prevent building near structures such as fast-travel points.",
    default: false,
  },
  {
    key: "bExistPlayerAfterLogout",
    type: "boolean",
    category: "features",
    label: "Exist After Logout",
    description: "Players enter sleeping state at current location on logout.",
    default: false,
  },
  {
    key: "bInvisibleOtherGuildBaseCampAreaFX",
    type: "boolean",
    category: "features",
    label: "Hide Other Guild Base FX",
    description: "Control visibility of other guilds' base area boundaries.",
    default: false,
  },
  {
    key: "bIsStartLocationSelectByMap",
    type: "boolean",
    category: "features",
    label: "Choose Start Location",
    description: "Allow players to choose their starting location.",
    default: true,
  },
  {
    key: "bShowPlayerList",
    type: "boolean",
    category: "features",
    label: "Show Player List",
    description: "Enable the player list on the ESC menu.",
    default: true,
  },
  {
    key: "bDisplayPvPItemNumOnWorldMap_BaseCamp",
    type: "boolean",
    category: "features",
    label: "Map: Base PvP Item Count",
    description: "Show PvP-exclusive item counts on bases on the map.",
    default: false,
  },
  {
    key: "bDisplayPvPItemNumOnWorldMap_Player",
    type: "boolean",
    category: "features",
    label: "Map: Player PvP Item Count",
    description: "Show player locations and PvP item counts on the map.",
    default: false,
  },

  // --- Game balances ---
  {
    key: "DayTimeSpeedRate",
    type: "number",
    category: "balances",
    label: "Day Time Speed",
    description: "Daytime progression speed.",
    default: 1,
  },
  {
    key: "NightTimeSpeedRate",
    type: "number",
    category: "balances",
    label: "Night Time Speed",
    description: "Nighttime progression speed.",
    default: 1,
  },
  {
    key: "ExpRate",
    type: "number",
    category: "balances",
    label: "EXP Rate",
    description: "EXP gain multiplier.",
    default: 1,
  },
  {
    key: "PalCaptureRate",
    type: "number",
    category: "balances",
    label: "Pal Capture Rate",
    description: "Capture rate multiplier.",
    default: 1,
  },
  {
    key: "PalSpawnNumRate",
    type: "number",
    category: "balances",
    label: "Pal Spawn Rate",
    description: "Pal spawn rate (impacts performance).",
    default: 1,
  },
  {
    key: "PalDamageRateAttack",
    type: "number",
    category: "balances",
    label: "Pal Damage (Attack)",
    description: "Damage dealt by Pals multiplier.",
    default: 1,
  },
  {
    key: "PalDamageRateDefense",
    type: "number",
    category: "balances",
    label: "Pal Damage (Defense)",
    description: "Damage taken by Pals multiplier.",
    default: 1,
  },
  {
    key: "PlayerDamageRateAttack",
    type: "number",
    category: "balances",
    label: "Player Damage (Attack)",
    description: "Damage dealt by players multiplier.",
    default: 1,
  },
  {
    key: "PlayerDamageRateDefense",
    type: "number",
    category: "balances",
    label: "Player Damage (Defense)",
    description: "Damage taken by players multiplier.",
    default: 1,
  },
  {
    key: "PlayerStomachDecreaceRate",
    type: "number",
    category: "balances",
    label: "Player Hunger Rate",
    description: "Player hunger depletion rate multiplier.",
    default: 1,
  },
  {
    key: "PlayerStaminaDecreaceRate",
    type: "number",
    category: "balances",
    label: "Player Stamina Rate",
    description: "Player stamina depletion rate multiplier.",
    default: 1,
  },
  {
    key: "PlayerAutoHPRegeneRate",
    type: "number",
    category: "balances",
    label: "Player HP Regen",
    description: "Player natural HP regen multiplier.",
    default: 1,
  },
  {
    key: "PlayerAutoHpRegeneRateInSleep",
    type: "number",
    category: "balances",
    label: "Player HP Regen (Sleep)",
    description: "Player HP regen while sleeping multiplier.",
    default: 1,
  },
  {
    key: "PalStomachDecreaceRate",
    type: "number",
    category: "balances",
    label: "Pal Hunger Rate",
    description: "Pal hunger depletion rate multiplier.",
    default: 1,
  },
  {
    key: "PalStaminaDecreaceRate",
    type: "number",
    category: "balances",
    label: "Pal Stamina Rate",
    description: "Pal stamina depletion rate multiplier.",
    default: 1,
  },
  {
    key: "PalAutoHPRegeneRate",
    type: "number",
    category: "balances",
    label: "Pal HP Regen",
    description: "Pal natural HP regen multiplier.",
    default: 1,
  },
  {
    key: "PalAutoHpRegeneRateInSleep",
    type: "number",
    category: "balances",
    label: "Pal HP Regen (Sleep)",
    description: "Pal HP regen while sleeping (in Palbox) multiplier.",
    default: 1,
  },
  {
    key: "BuildObjectDamageRate",
    type: "number",
    category: "balances",
    label: "Building Damage Rate",
    description: "Damage multiplier to buildings.",
    default: 1,
  },
  {
    key: "BuildObjectDeteriorationDamageRate",
    type: "number",
    category: "balances",
    label: "Building Decay Rate",
    description: "Building decay speed multiplier.",
    default: 1,
  },
  {
    key: "CollectionDropRate",
    type: "number",
    category: "balances",
    label: "Collection Drop Rate",
    description: "Gatherable items multiplier.",
    default: 1,
  },
  {
    key: "CollectionObjectHpRate",
    type: "number",
    category: "balances",
    label: "Collection Object HP",
    description: "Gatherable objects health multiplier.",
    default: 1,
  },
  {
    key: "CollectionObjectRespawnSpeedRate",
    type: "number",
    category: "balances",
    label: "Collection Respawn Speed",
    description: "Gatherable objects respawn interval multiplier.",
    default: 1,
  },
  {
    key: "EnemyDropItemRate",
    type: "number",
    category: "balances",
    label: "Enemy Drop Rate",
    description: "Dropped item quantity multiplier.",
    default: 1,
  },
  {
    key: "DeathPenalty",
    type: "enum",
    category: "balances",
    label: "Death Penalty",
    description:
      "None / Item / ItemAndEquipment / All (items + team Pals).",
    enumValues: ["None", "Item", "ItemAndEquipment", "All"],
    default: "All",
  },
  {
    key: "bPalLost",
    type: "boolean",
    category: "balances",
    label: "Permanent Pal Loss",
    description: "Permanently lose Pals on death.",
    default: false,
  },
  {
    key: "GuildPlayerMaxNum",
    type: "number",
    category: "balances",
    label: "Guild Max Players",
    description: "Max players per guild.",
    default: 20,
  },
  {
    key: "GuildRejoinCooldownMinutes",
    type: "number",
    category: "balances",
    label: "Guild Rejoin Cooldown",
    description: "Guild rejoin cooldown (minutes).",
    default: 0,
  },
  {
    key: "PalEggDefaultHatchingTime",
    type: "number",
    category: "balances",
    label: "Huge Egg Hatch Time (hours)",
    description: "Time to hatch a Huge Egg in hours.",
    default: 72,
  },
  {
    key: "EquipmentDurabilityDamageRate",
    type: "number",
    category: "balances",
    label: "Equipment Durability Rate",
    description: "Equipment durability loss multiplier.",
    default: 1,
  },
  {
    key: "ItemWeightRate",
    type: "number",
    category: "balances",
    label: "Item Weight Rate",
    description: "Item weight multiplier.",
    default: 1,
  },
  {
    key: "ItemCorruptionMultiplier",
    type: "number",
    category: "balances",
    label: "Item Corruption Rate",
    description: "Item corruption speed multiplier.",
    default: 1,
  },
  {
    key: "MonsterFarmActionSpeedRate",
    type: "number",
    category: "balances",
    label: "Farm Action Speed",
    description: "Item production speed multiplier from grazing.",
    default: 1,
  },
  {
    key: "SupplyDropSpan",
    type: "number",
    category: "balances",
    label: "Supply Drop Interval (min)",
    description: "Meteorite / supply drop interval in minutes.",
    default: 180,
  },
  {
    key: "BlockRespawnTime",
    type: "number",
    category: "balances",
    label: "Respawn Cooldown (sec)",
    description: "Cooldown before you can respawn after death.",
    default: 0,
  },
  {
    key: "RespawnPenaltyDurationThreshold",
    type: "number",
    category: "balances",
    label: "Respawn Penalty Threshold (sec)",
    description:
      "Survival-time threshold for applying RespawnPenaltyTimeScale.",
    default: 0,
  },
  {
    key: "RespawnPenaltyTimeScale",
    type: "number",
    category: "balances",
    label: "Respawn Penalty Scale",
    description: "Multiplier applied to the respawn cooldown.",
    default: 1,
  },
  {
    key: "DenyTechnologyList",
    type: "stringList",
    category: "balances",
    label: "Deny Technology List",
    description: "Disable specific technologies by Technology ID.",
    default: [],
  },
  {
    key: "bAdditionalDropItemWhenPlayerKillingInPvPMode",
    type: "boolean",
    category: "balances",
    label: "PvP Kill Extra Drop",
    description: "Drop a special item when a player is killed in PvP.",
    default: false,
  },
  {
    key: "AdditionalDropItemWhenPlayerKillingInPvPMode",
    type: "string",
    category: "balances",
    label: "PvP Kill Drop Item ID",
    description: "Item ID to drop on PvP kill when extra drop is enabled.",
    default: "",
  },
  {
    key: "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
    type: "number",
    category: "balances",
    label: "PvP Kill Drop Quantity",
    description: "Quantity of the special PvP kill drop item.",
    default: 1,
  },
];

export const INI_FIELD_MAP = Object.fromEntries(
  INI_FIELDS.map((f) => [f.key, f]),
) as Record<string, IniFieldDef>;

export const INI_CATEGORIES: {
  id: IniCategory;
  label: string;
  description: string;
}[] = [
  {
    id: "performance",
    label: "Performance",
    description: "Base limits, building caps, and replication distance.",
  },
  {
    id: "server",
    label: "Server management",
    description: "Name, passwords, ports, REST/RCON, crossplay, backups.",
  },
  {
    id: "features",
    label: "Features",
    description: "PvP, hardcore, travel, invaders, voice, randomizer, guilds.",
  },
  {
    id: "balances",
    label: "Game balances",
    description: "Rates, death penalty, timers, and technology denylist.",
  },
];
